[package]
name = "sqlx-example-postgres-hello_world"
version = "0.1.0"
edition = "2018"

[dependencies]
sqlx = { path = "../../..", features = [ "postgres" ] }
async-std = { version = "1.5.0", features = [ "attributes" ] }
anyhow = "1.0.26"
